name: Android CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "dev"
    paths:
      - "android/**"

jobs:
  android-lint:
    name: Run android linter on android directory
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Run android lint
        run: chmod +x gradlew && ./gradlew lint

      - name: Generate annotation
        uses: yutailang0119/action-android-lint@v4
        with:
          ignore-warnings: false